name: Build and Deploy Docs

on:
  push:
    branches:
      - main # Or your default branch

permissions:
  contents: write # Allow write access to checkout and push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Or your project's Python version

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-docs.txt
          pip install -e .

      - name: Build documentation
        run: mkdocs build --verbose

      - name: Remove any existing CNAME file
        run: |
          if [ -f "./site/CNAME" ]; then
            rm ./site/CNAME
            echo "Removed existing CNAME file"
          else
            echo "No CNAME file found"
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true
          # Explicitly disable custom domain to use default GitHub Pages URL
          cname: false
